name: Validate API and Publish on SwaggerHub

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Validate-Design-on-Swaggerhub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install SwaggerHub CLI
        run: |
          npm install swaggerhub-cli -g
      - name: Check the API definition exists
        env:
          SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        run: |
          swaggerhub api:get Demo_Org/Automation/1.0.1
      - name: Validate definition
        env:
          SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        run: |
          swaggerhub api:validate Demo_Org/Automation/1.0.1
          
  Publish-Documentation:
    runs-on: ubuntu-latest
    needs: Validate-Design-on-Swaggerhub
    steps:
      - uses: actions/checkout@v2
      - name: Use Nodejs 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install SwaggerHub CLI
        run: |
          npm install swaggerhub-cli -g
      - name: Publish the API definition
        env:
          SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        run: |
          swaggerhub api:publish Demo_Org/Automation/1.0.1
      - name: Make new version the default
        env:
          SWAGGERHUB_API_KEY: ${{secrets.SWAGGERHUB_API_KEY}}
        run: |
          swaggerhub api:setdefault Demo_Org/Automation/1.0.1
          
